import type { PresentationEvent } from "@/lib/event-schema";

export type ExhibitKind = "archive" | "computer" | "genesis" | "pizza" | "mining" | "halving" | "protocol" | "lightning" | "market" | "exchange" | "custody" | "security" | "insolvency" | "law" | "court" | "commerce" | "treasury" | "media" | "memorial" | "auction" | "assembly" | "charity" | "inscription" | "atm";
export type ExhibitDesign = { kind: ExhibitKind; motif: string; state: string };

// Editorial assignments, not category/keyword guesses. Related events can share
// architecture, but their actual mechanism and historical stage must stay distinct.
// These are symbolic dioramas, NOT reconstructions of premises or official seals.
const designs: Record<string, ExhibitDesign> = {};
function assign(kind: ExhibitKind, motif: string, state: string, slugs: string) {
  for (const slug of slugs.split(/\s+/).filter(Boolean)) {
    if (designs[slug]) throw new Error(`Duplicate exhibit design: ${slug}`);
    designs[slug] = { kind, motif, state };
  }
}

assign("archive", "blind-signature", "research", `chaum-blind-signatures-paper`);
assign("archive", "mint", "research", `digicash-founded`);
assign("archive", "postage", "research", `hashcash-proposed`);
assign("archive", "distributed-ledger", "research", `b-money-proposed`);
assign("archive", "reusable-token", "research", `rpow-reusable-proofs-of-work`);
assign("archive", "proof-chain", "research", `bit-gold-described`);
assign("archive", "whitepaper", "published", `bitcoin-white-paper-announced`);
assign("computer", "mail", "sent", `cypherpunks-mailing-list-founded satoshi-contacts-wei-dai satoshi-final-known-email`);
assign("computer", "domain", "registered", `bitcoin-org-domain-registered`);
assign("computer", "repository", "registered", `bitcoin-sourceforge-project-registered`);
assign("computer", "client", "running", `hal-finney-running-bitcoin`);
assign("computer", "transaction", "sent", `first-person-to-person-bitcoin-transaction first-bitcoin-fiat-trade`);
assign("computer", "forum", "published", `satoshi-p2p-foundation-announcement bitcointalk-forum-launched satoshi-last-public-forum-post hodl-post-written`);
assign("computer", "wiki", "published", `bitcoin-wiki-founded`);
assign("computer", "release", "released", `bitcoin-version-0-1-released bitcoin-version-0-2-released bitcoin-version-0-3-released bitcoin-qt-version-0-5-released bitcoin-qt-version-0-8-released bitcoin-core-version-0-9-released bitcoin-core-version-0-10-released bitcoin-core-version-0-12-released bitcoin-core-0-13-1-segwit-release`);
assign("genesis", "newspaper", "mined", `genesis-block-mined`);
assign("pizza", "offer", "pending", `bitcoin-pizza-offer-posted`);
assign("pizza", "purchase", "complete", `bitcoin-pizza-purchase`);
assign("charity", "faucet", "open", `bitcoin-faucet-launched`);
assign("mining", "difficulty", "increase", `first-bitcoin-difficulty-increase`);
assign("mining", "gpu", "running", `early-gpu-bitcoin-mining first-public-opencl-miner`);
assign("mining", "split-reward", "shared", `first-split-mining-reward`);
assign("mining", "pool", "shared", `slush-pool-first-block`);
assign("mining", "peer-pool", "shared", `p2pool-first-mainnet-block`);
assign("mining", "asic", "shipping", `first-bitcoin-asics-ship`);
assign("mining", "concentration", "warning", `ghash-io-crosses-half-hashrate`);
assign("mining", "shutdown", "proposed", `china-financial-stability-committee-mining-crackdown`);
assign("mining", "shutdown", "closed", `sichuan-bitcoin-mines-shut-down`);
assign("mining", "migration", "moving", `great-mining-migration-difficulty-drop`);
assign("mining", "permit", "restricted", `new-york-proof-of-work-moratorium`);
assign("mining", "permit", "enacted", `russia-bitcoin-mining-framework-law`);
assign("mining", "supply", "milestone", `bitcoin-twenty-million-mined`);
assign("halving", "first", "50 → 25", `first-bitcoin-halving`);
assign("halving", "second", "25 → 12.5", `second-bitcoin-halving`);
assign("halving", "third", "12.5 → 6.25", `third-bitcoin-halving`);
assign("halving", "fourth", "6.25 → 3.125", `fourth-bitcoin-halving`);
assign("protocol", "overflow", "repaired", `bitcoin-value-overflow-incident`);
assign("protocol", "patch", "repaired", `bitcoin-inflation-bug-fixed`);
assign("protocol", "proposal", "published", `bip-process-established`);
assign("protocol", "key-tree", "proposed", `bip32-hierarchical-deterministic-wallets`);
assign("protocol", "seed", "proposed", `bip39-mnemonic-seed-phrases`);
assign("protocol", "script", "active", `p2sh-bip16-activates`);
assign("protocol", "height", "active", `bip34-block-height-activation`);
assign("protocol", "reorganization", "0.7-canonical", `march-2013-chain-split`);
assign("protocol", "split", "resolved", `bip66-activation-chain-split`);
assign("protocol", "split", "released", `bitcoin-xt-block-size-release`);
assign("protocol", "clock", "active", `csv-soft-fork-activates`);
assign("protocol", "segwit", "signaling", `segwit-miner-signaling-begins`);
assign("protocol", "segwit", "user-activated", `uasf-bip148`);
assign("protocol", "segwit", "locked-in", `segwit-locks-in`);
assign("protocol", "segwit", "active", `segwit-activates`);
assign("protocol", "split", "forked", `bitcoin-cash-fork bitcoin-cash-bitcoin-sv-split`);
assign("protocol", "split", "cancelled", `segwit2x-hard-fork-cancelled`);
assign("protocol", "sidechain", "active", `liquid-sidechain-launch`);
assign("protocol", "taproot", "proposed", `taproot-bips-published`);
assign("protocol", "taproot", "locked-in", `taproot-locks-in`);
assign("protocol", "taproot", "active", `taproot-activates`);
assign("protocol", "computation", "proposed", `bitvm-paper`);
assign("protocol", "data", "released", `bitcoin-core-v30-op-return-policy`);
assign("lightning", "channel", "proposed", `lightning-network-paper`);
assign("lightning", "channel", "beta", `lnd-first-mainnet-beta`);
assign("lightning", "relay", "active", `lightning-torch-begins`);
assign("lightning", "wide-channel", "released", `lnd-wumbo-channels`);
assign("lightning", "assets", "proposed", `taro-protocol-announced`);
assign("market", "rate", "first", `new-liberty-standard-exchange-rate`);
assign("market", "capitalization", "high", `bitcoin-market-cap-one-million bitcoin-market-cap-one-billion`);
assign("market", "price", "high", `bitcoin-dollar-parity bitcoin-2011-market-peak bitcoin-price-reaches-100-dollars bitcoin-price-reaches-1000-dollars bitcoin-2017-cycle-high bitcoin-breaks-2017-price-record bitcoin-all-time-high-november-2021 bitcoin-crosses-one-hundred-thousand bitcoin-2025-all-time-high`);
assign("market", "price", "low", `bitcoin-2018-cycle-low bitcoin-2022-cycle-low`);
assign("market", "price", "crash", `april-2013-bitcoin-market-crash bitcoin-black-thursday bitcoin-2026-drawdown`);
assign("market", "leverage", "liquidation", `october-2025-liquidation-event`);
assign("market", "index", "listed", `microstrategy-added-nasdaq100`);
assign("exchange", "spot", "open", `bitcoin-market-opens mt-gox-bitcoin-exchange-launches coinbase-founded coinbase-exchange-launches gemini-opens-for-trading binance-founded`);
assign("exchange", "handover", "transferred", `mt-gox-sold-to-mark-karpeles`);
assign("exchange", "futures", "open", `cboe-bitcoin-futures-launch cme-bitcoin-futures-launch`);
assign("exchange", "delivery", "open", `bakkt-bitcoin-futures-launch`);
assign("exchange", "futures", "closed", `cboe-stops-new-bitcoin-futures`);
assign("exchange", "delivery", "announced", `bakkt-announced`);
assign("exchange", "options", "open", `cme-bitcoin-options-launch us-bitcoin-etf-options-trading-begins`);
assign("exchange", "options", "approved", `sec-approves-ibit-options`);
assign("exchange", "trust", "open", `grayscale-bitcoin-trust-launched`);
assign("exchange", "listing", "listed", `coinbase-direct-listing`);
assign("exchange", "futures-etf", "open", `proshares-bito-launch`);
assign("exchange", "spot-etf", "filed", `blackrock-files-spot-bitcoin-etp`);
assign("exchange", "spot-etf", "rejected", `sec-rejects-winklevoss-bitcoin-etp-again`);
assign("exchange", "spot-etf", "approved", `us-spot-bitcoin-etps-approved`);
assign("exchange", "spot-etf", "open", `purpose-bitcoin-etf-launch us-spot-bitcoin-etps-start-trading hong-kong-spot-bitcoin-etfs blackrock-europe-bitcoin-etp`);
assign("custody", "vault", "open", `fidelity-digital-assets-live bny-mellon-digital-asset-unit`);
assign("custody", "charter", "approved", `itbit-new-york-trust-charter kraken-wyoming-bank-charter`);
assign("custody", "peg", "issued", `tether-launched`);
assign("security", "wallet", "stolen", `allinvain-wallet-theft bitstamp-2015-security-breach bitfinex-2016-security-breach binance-bitcoin-hot-wallet-hack dmm-bitcoin-hack`);
assign("security", "exchange", "breached", `mt-gox-2011-security-breach bitcoinica-may-2012-hack`);
assign("security", "server", "breached", `linode-bitcoin-theft`);
assign("security", "nem", "stolen", `coincheck-hack`);
assign("security", "ether", "stolen", `bybit-exchange-theft`);
assign("security", "account", "scam", `twitter-compromise-bitcoin-scam sec-x-account-false-etf-post`);
assign("security", "data", "stolen", `coinbase-customer-data-theft`);
assign("security", "recovered", "recovered", `colonial-pipeline-ransom-recovered`);
assign("insolvency", "ponzi", "closed", `bitcoin-savings-and-trust-closes plustoken-ponzi-collapse`);
assign("insolvency", "withdrawals", "frozen", `mt-gox-halts-bitcoin-withdrawals celsius-pauses-withdrawals`);
assign("insolvency", "deposits", "halted", `btc-china-halts-yuan-deposits`);
assign("insolvency", "court-files", "bankruptcy", `mt-gox-files-for-bankruptcy voyager-digital-bankruptcy ftx-chapter-11 blockfi-bankruptcy genesis-global-bankruptcy`);
assign("insolvency", "creditors", "protection", `quadrigacx-creditor-protection`);
assign("insolvency", "creditors", "rehabilitation", `mt-gox-civil-rehabilitation`);
assign("insolvency", "creditors", "repaying", `mt-gox-bitcoin-repayments-begin`);
assign("insolvency", "liquidation", "winding-down", `three-arrows-capital-liquidation silvergate-voluntary-liquidation signature-bank-closed`);
assign("insolvency", "mine", "bankruptcy", `core-scientific-bankruptcy`);
assign("insolvency", "peg", "broken", `terra-collapse`);
assign("law", "report", "published", `ecb-virtual-currency-schemes-report`);
assign("law", "licensing", "guidance", `fincen-virtual-currency-guidance`);
assign("law", "classification", "recognized", `germany-bitcoin-unit-of-account cftc-bitcoin-commodity-coinflip`);
assign("law", "tax", "guidance", `irs-treats-bitcoin-as-property`);
assign("law", "licensing", "proposed", `new-york-proposes-bitlicense`);
assign("law", "licensing", "enacted", `new-york-final-bitlicense japan-passes-virtual-currency-regulation`);
assign("law", "licensing", "effective", `japan-crypto-exchange-registration-begins hong-kong-vasp-licensing-effective brazil-crypto-framework-effective`);
assign("law", "bank-gate", "restricted", `china-bitcoin-risk-notice nigeria-central-bank-crypto-restrictions`);
assign("law", "exchange-gate", "closed", `china-exchanges-announce-closures china-declares-crypto-transactions-illegal`);
assign("law", "token-sale", "prohibited", `china-ico-ban`);
assign("law", "reporting", "guidance", `fatf-virtual-assets-travel-rule`);
assign("law", "custody", "permitted", `germany-bank-crypto-custody-law occ-allows-bank-crypto-custody`);
assign("law", "network", "permitted", `occ-banks-blockchain-nodes`);
assign("law", "payment-gate", "prohibited", `turkey-crypto-payment-ban`);
assign("law", "tender", "announced", `el-salvador-bitcoin-law-announced`);
assign("law", "tender", "passed", `el-salvador-bitcoin-law-passed central-african-republic-bitcoin-legal-tender`);
assign("commerce", "tender", "effective", `el-salvador-bitcoin-law-effective`);
assign("law", "tender", "removed", `central-african-republic-removes-bitcoin-legal-tender`);
assign("law", "tender", "voluntary", `el-salvador-amends-bitcoin-law`);
assign("law", "tender", "agreement", `el-salvador-imf-bitcoin-agreement`);
assign("law", "reporting", "enacted", `us-infrastructure-act-crypto-broker-reporting`);
assign("law", "account-gate", "frozen", `canada-emergencies-act-account-freezes`);
assign("law", "order", "directed", `us-digital-assets-executive-order us-digital-financial-technology-order us-fintech-regulatory-integration-order`);
assign("law", "mica", "agreement", `eu-mica-political-agreement`);
assign("law", "mica", "adopted", `eu-council-adopts-mica`);
assign("law", "mica", "effective", `mica-fully-applies`);
assign("law", "mica", "deadline", `mica-transition-period-ends`);
assign("law", "sanctions", "restricted", `tornado-cash-sanctioned`);
assign("law", "bank-standard", "published", `basel-cryptoasset-bank-standard`);
assign("law", "issuance", "enacted", `el-salvador-digital-asset-issuance-law`);
assign("law", "framework", "enacted", `uk-financial-services-markets-act-crypto`);
assign("law", "accounting", "adopted", `fasb-crypto-fair-value-standard`);
assign("law", "bank-gate", "reopened", `nigeria-lifts-crypto-banking-restrictions`);
assign("law", "house-bill", "passed-house", `fit21-passes-us-house clarity-act-passes-house`);
assign("law", "committee-bill", "advanced", `clarity-act-senate-banking-advances`);
assign("law", "custody-rule", "vetoed", `biden-vetoes-sab121-repeal`);
assign("law", "custody-rule", "rescinded", `sec-rescinds-sab121`);
assign("law", "custody-rule", "removed", `occ-removes-crypto-nonobjection-requirement`);
assign("law", "investment", "authorized", `new-hampshire-bitcoin-investment-law`);
assign("law", "stablecoin", "enacted", `genius-act-signed`);
assign("court", "ruling", "decided", `sec-v-shavers-bitcoin-investments-ruling hodlonaut-wins-norway-wright-case`);
assign("court", "tax", "exempted", `eu-bitcoin-vat-exemption`);
assign("court", "bank-gate", "overturned", `india-supreme-court-overturns-banking-ban`);
assign("court", "appeal", "vacated", `grayscale-wins-sec-appeal`);
assign("court", "identity", "rejected", `copa-v-wright-identity-ruling`);
assign("court", "charges", "charged", `charlie-shrem-charged btc-e-seized-vinnik-charged doj-charges-bitmex-founders samourai-wallet-founders-charged`);
assign("court", "complaint", "filed", `sec-sues-binance-and-coinbase`);
assign("court", "settlement", "guilty-pleas", `binance-us-criminal-settlement`);
assign("court", "seizure", "seized", `us-seizes-mt-gox-payment-accounts silk-road-seized us-seizes-silk-road-bitcoin`);
assign("commerce", "payment-terminal", "open", `bitpay-founded paypal-announces-crypto-service`);
assign("commerce", "pub", "accepting", `room77-accepts-bitcoin`);
assign("commerce", "publishing", "accepting", `wordpress-accepts-bitcoin`);
assign("commerce", "parcels", "accepting", `overstock-accepts-bitcoin`);
assign("commerce", "computer", "accepting", `dell-accepts-bitcoin microsoft-accepts-bitcoin`);
assign("commerce", "marketplace", "open", `openbazaar-one-point-zero-launch`);
assign("commerce", "games", "accepting", `steam-accepts-bitcoin`);
assign("commerce", "games", "stopped", `steam-drops-bitcoin`);
assign("commerce", "car", "stopped", `tesla-suspends-bitcoin-payments`);
assign("treasury", "corporate", "buying", `microstrategy-first-bitcoin-treasury-purchase square-buys-bitcoin massmutual-bitcoin-purchase`);
assign("treasury", "car", "buying", `tesla-bitcoin-purchase-disclosed`);
assign("treasury", "car", "selling", `tesla-sells-most-bitcoin`);
assign("treasury", "corporate", "selling", `strategy-sells-bitcoin`);
assign("treasury", "pension", "allocated", `wisconsin-pension-bitcoin-etf-holdings`);
assign("treasury", "retirement", "option", `fidelity-bitcoin-401k-option`);
assign("treasury", "assessment", "rejected", `microsoft-shareholders-reject-bitcoin-assessment`);
assign("treasury", "national", "established", `us-strategic-bitcoin-reserve`);
assign("treasury", "state", "established", `texas-strategic-bitcoin-reserve-law`);
assign("media", "news", "published", `bitcoin-featured-on-slashdot time-magazine-covers-bitcoin gawker-silk-road-bitcoin-story`);
assign("media", "film", "released", `weusecoins-video-released`);
assign("media", "identity-claim", "disputed", `craig-wright-claims-satoshi-identity`);
assign("memorial", "finney", "remembrance", `hal-finney-dies`);
assign("auction", "paddles", "auction", `us-marshals-first-bitcoin-auction`);
assign("auction", "sale", "completed", `saxony-completes-seized-bitcoin-sale`);
assign("assembly", "conference", "convened", `first-bitcoin-conference-new-york`);
assign("assembly", "foundation", "founded", `bitcoin-foundation-formed blockstream-founded`);
assign("assembly", "negotiations", "agreement", `hong-kong-scaling-agreement new-york-agreement-segwit2x`);
assign("assembly", "hearing", "testimony", `us-senate-virtual-currency-hearings`);
assign("assembly", "speech", "proposed", `trump-bitcoin-nashville-policy-speech`);
assign("assembly", "committee", "appointed", `sec-crypto-task-force texas-bitcoin-reserve-advisory-committee`);
assign("charity", "donations", "accepting", `wikileaks-accepts-bitcoin unicef-cryptocurrency-fund ukraine-crypto-donations-surge`);
assign("charity", "donations", "suspended", `eff-suspends-bitcoin-donations`);
assign("inscription", "art", "launched", `ordinals-protocol-launch`);
assign("inscription", "art", "milestone", `ordinals-ten-million-inscriptions`);
assign("inscription", "token", "experiment", `brc20-experiment-deployed`);
assign("inscription", "runes", "launched", `runes-protocol-launch`);
assign("atm", "cash", "open", `first-public-bitcoin-atm`);

export const exhibitDesigns: Readonly<Record<string, Readonly<ExhibitDesign>>> = designs;
export function exhibitDesign(event: Pick<PresentationEvent, "slug">): Readonly<ExhibitDesign> {
  // A safe archival display for future records; coverage tests require an explicit
  // editorial assignment for every record currently in the corpus.
  return designs[event.slug] ?? { kind: "archive", motif: "record", state: "documented" };
}
export function exhibitKind(event: Pick<PresentationEvent, "slug">): ExhibitKind {
  return exhibitDesign(event).kind;
}
